### ISSUE TITLE
Enforce that people only vote either yes OR no in polls

### ISSUE THREAD

**Issue by elkowar** [unixporn/trup#43]
People voting for both yes and no in polls makes the poll seem more controversial than it is, so trup should be able to automatically remove the "yes" reaction if the user reacts with "no" and vice versa.
I'd be interested in trying to implement this too, if you think it's a good idea.

**Comment by DRG-developer** [comment]
I don't think that's possible. You mean the server feeback right? That would require the bot to do something on behalf of the user. Or can you remove emotes that people add as a mod?

**Comment by eepykate** [comment]
@DRG-developer Bots can remove reactions. I'm not sure about higher roles, but because discord's role system is pretty stupid it's safe to assume that they can, since if you have the delete message perm you can delete stuff from an admin, even if your role is way further down and only has that perm.

And polls aren't the same as posts in #server-feedback.

(go to #bots then run `!poll test`)

**Comment by eepykate** [comment]
Important: Make sure trup won't remove its own reactions.

**Comment by elkowar** [comment]
it was discussed that we should, when enforcing "single-vote-only", also have a "i don't care" option. two questions regarding that:
- was that decision final?
- what should the reaction for that be? the 🤷‍♂️ emoji? that's questionable because we'd have to decide on one gender for it. what else would be a good emoji for it?

**Comment by DRG-developer** [comment]
First of all:
Fuck off about what gender, it will be male, because 90% of the discord server is male, color: yellow, so no thing about racism.

Next: why do we need an standardised “I Don't Care” emoji? If you don't care on hillary vs trump, you don't vote. You can't count “i don't care”'s, so lets make that a “if you wanna you can do it, even if you downvote or upvote” ?

**Comment by elkowar** [comment]
yea no we really cannot just "fuck off" about the gender. Even if 90% of the community is male, i think we should - if in any way possible - avoid having a gender-specific emoji there

The idea about the "I don't care" emoji was mostly relevant for moderator-internal stuff, where we do care about how many people have actually voted / looked at a poll. see, a poll where there are 2 votes pro and 0 votes against a thing has a very different meaning depending on if everyone who read it voted (only two people that are able to vote, everyone votes pro) vs if half the people looked at it and don't care (a lot of "i don't care" votes) vs many people just not having looked at the poll at all (there could still be a big majority that is would vote against XY, they have just not read it)

**Comment by DRG-developer** [comment]
Okay, then it's female, because only feminsts are talking about that.

But please explain why we should avoid 1 gender? Remember, we are not a political party?
Or as mr torvalds once said: “sometimes a project becomes so much about political correctness it isn't about the code anymore”. Also, we can implement political correctness afterwards, if people actually are complaining, which, spoiler alert, they won't.
Anyway, i am sure @phisch will exactly understand what i am talking about.

**Comment by elkowar** [comment]
finding a "i don't care" emoji that is not gender specific should not be as hard as forcing political correctness into a whole codebase tho. This is enduser stuff. Not being a political party doesn't mean we should actively ignore gender neutrality. I personally couldn't care less. But there would be people that complained, and finding a better solution shouldnt be hard. A good alternative would be 😐, for example

**Comment by aosync** [comment]
Why not using the female shrug because girls are cool 😎

**Comment by DRG-developer** [comment]
I find it so weird, that there are so many things that go completely ignored, which over 5% of people find frustrating, but when the media picks something up,  everything has to move for gender neutrality. Just because the i don’t care emoji is male or female, doesn't mean that male or females are worth more or less. It's just a representation of the whole. And nobody cared about it, until the media gave it attention. Just like i don't care if your are LHBT or whatever, i will treat you the same as anyone else, but that's not good enough anymore, they have to be treated specially with their own toilets and stuff, and *that* is where i draw the line.

And if 5 users complain, we can safely ignore them, cause there are many more people who have different thoughts on corona, and they get ignored too, or get pushed in the box of “conspiracy theory”. Not every individual is special, not everyone can be whoever he or she wants to be. If everyone is special, nobody is special. 
I am not special either.

And lets make it female, cause then the feminists are happy, and the Male rights activists aren't such annoying people, because they haven't gotten media attention yet, and thus so don't realize how amazing it is to fuck over every tiny detail

**Comment by mlvzk** [comment]
![image](https://user-images.githubusercontent.com/44906333/88383535-024e2980-cdab-11ea-9005-937ff785b392.png)
We should use one of the squares, I think the yellow square would be alright

**Comment by elkowar** [comment]
So then we’d do squares for all of them tho, right?

**Comment by elkowar** [comment]
After looking at using the squares, they seemed a bit to non-obvious.
Given the fact that there are actually _three_ shrug emoji (person, man, women), so i'll just go with person shrugging (🤷)
